from level_3.settings3 import *
from level_3.map3 import *
from level_3.player3 import *
from level_3.raycasting3 import *
from level_3.object_renderer3 import *
from level_3.sprite_object3 import *
from level_3.object_handler3 import *
from level_3.weapon3 import * 
from level_3.sound3 import * 
from level_3.pathfinding3 import *
from level_3.npc3 import *