from level_2.settings2 import *
from level_2.map2 import *
from level_2.player2 import *
from level_2.raycasting2 import *
from level_2.object_renderer2 import *
from level_2.sprite_object2 import *
from level_2.object_handler2 import *
from level_2.weapon2 import * 
from level_2.sound2 import * 
from level_2.pathfinding2 import *
from level_2.npc2 import *